const $=id=>document.getElementById(id);
const makeId=()=>{try{if(window.crypto?.randomUUID)return window.crypto.randomUUID().replace(/-/g,'');if(window.crypto?.getRandomValues){const a=new Uint8Array(24);window.crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}}catch{}return 'saarthi'+Date.now().toString(36)+Math.random().toString(36).slice(2)};
let SESSION=localStorage.getItem('saarthi_session');if(!SESSION||!/^[a-f0-9]{16,64}$/i.test(SESSION)){SESSION=makeId();localStorage.setItem('saarthi_session',SESSION)}
let AUTH=localStorage.getItem('saarthi_token')||'',state={hasData:false,analytics:null},recognition=null,listening=false,timerHandle=null,requestStarted=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
const soundEnabled=()=>localStorage.getItem('saarthi_sound')!=='0';
function ping(kind='tap'){if(!soundEnabled()||!window.AudioContext&&!window.webkitAudioContext)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain(),f={tap:520,success:700,error:180,open:400}[kind]||520;o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(kind==='error'?.035:.018,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.09);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.1);setTimeout(()=>c.close(),180)}catch{}}
async function api(path,opt={}){const headers={...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),'x-saarthi-session':SESSION,...(AUTH?{'Authorization':`Bearer ${AUTH}`}:{ }),...(opt.headers||{})};let r,j;try{r=await fetch(path,{...opt,headers});j=await r.json().catch(()=>({}))}catch{throw Error('Saarthi backend is unavailable. Keep npm start running and open http://localhost:3000.')}if(!r.ok)throw Error(j?.error?.message||j?.error||`Request failed (${r.status})`);return j}
const viewNames={home:['MY MONEY','Your financial cockpit'],transactions:['CANONICAL LEDGER','Your transactions'],investigate:['UNDERSTAND','Find what matters'],decisions:['DECIDE','Digital Twin'],data:['MY DATA','Bring your financial life here']};
function show(view){if(!viewNames[view])return;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-'+view)?.classList.add('active');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('view-kicker').textContent=viewNames[view][0];$('view-title').textContent=viewNames[view][1];$('sidebar')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});ping('tap')}
function render(a){state.analytics=a;if(!a){$('data-pill').textContent='No data';$('health').textContent='—';$('metrics').innerHTML='';$('flow').innerHTML='<div class="empty">Load your data to see your money flow.</div>';$('signals').innerHTML=`<div class="signal"><b>${t('Your financial picture starts here.')}</b><p>${t('Import a ledger or use the demo dataset to unlock Saarthi’s analysis.')}</p></div>`;return}
$('data-pill').textContent=`${a.transactionCount||0} records`;$('health').textContent=a.healthScore??'—';$('coverage').textContent=a.audit?.coverage||'DATA READY';$('hero-sub').textContent=`${a.transactionCount||0} ${t('transactions are loaded.')} Saarthi can now ${t('audit, compare and simulate around your financial picture.')}`;
const vals=[['Income',a.totalIncome,'Total money in'],['Expenses',a.totalExpenses,'Total money out'],['Surplus',a.netSavings,'Income minus expenses'],['Savings rate',`${a.savingsRate||0}%`,'Current calculated rate']];$('metrics').innerHTML=vals.map(([n,v,s])=>`<div class="metric"><span>${n.toUpperCase()}</span><strong>${typeof v==='string'?esc(v):money(v)}</strong><small>${s}</small></div>`).join('');
const flow=[['Income',a.totalIncome],['Expenses',a.totalExpenses],['Surplus',Math.max(0,a.netSavings)]],max=Math.max(...flow.map(x=>Math.abs(Number(x[1]))||1));$('flow').innerHTML=flow.map(([n,v])=>`<div class="flow-row"><b>${n}</b><div class="bar"><i style="width:${Math.min(100,Math.round(Math.abs(v)/max*100))}%"></i></div><strong>${money(v)}</strong></div>`).join('');
const sig=(a.insights||[]).slice(0,4);$('signals').innerHTML=sig.length?sig.map(x=>`<div class="signal"><b>${esc(x.title||'Signal')}</b><p>${esc(x.text||x.evidence||'')}</p></div>`).join(''):'<div class="signal"><b>No immediate signal.</b><p>Run a full audit for deeper evidence-backed checks.</p></div>'}
async function load(){try{const j=await api('/api/state');state.hasData=!!j.hasData;render(j.hasData?j.analytics:null);if(j.hasData)await loadTx()}catch(e){render(null)}}
async function loadTx(){try{const j=await api('/api/transactions'),rows=j.transactions||[];$('tx-count').textContent=`${rows.length} transactions`;$('tx-body').innerHTML=rows.map(t=>`<tr><td>${esc(t.date)}</td><td>${esc(t.merchant||t.description)}</td><td>${esc(t.category)}</td><td>${esc(t.direction)}</td><td>${money(t.absAmount??Math.abs(t.amount))}</td><td>${esc(t.sourceRow??'—')}</td></tr>`).join('');$('tx-empty').classList.toggle('hidden',rows.length>0)}catch{}}
function agentBusy(on,text='Thinking…'){const el=$('agent-status');el.classList.toggle('busy',on);el.classList.remove('error');$('agent-status-text').textContent=text;if(on){requestStarted=performance.now();clearInterval(timerHandle);timerHandle=setInterval(()=>{$('agent-timer').textContent=`${((performance.now()-requestStarted)/1000).toFixed(1)}s`},100)}else{clearInterval(timerHandle);$('agent-timer').textContent=''}}
function trace(inv){if(!inv)return '';const labels={investigate_finances:'Map finances',get_financial_summary:'Calculate summary',audit_transactions:'Audit ledger',find_category_spending:'Inspect categories',compare_months:'Compare periods',calculate_goal:'Test goal',calculate_affordability:'Check affordability',run_what_if:'Run simulation'};return `<div class="agent-trace">${(inv.plan?.steps||[]).map(s=>`<div>${esc(labels[s]||s)} ✓</div>`).join('')}</div>`}
async function ask(q){if(!q)return;show('home');$('hero-question').value=q;$('hero-ask').disabled=true;agentBusy(true,t('Investigating your request'));try{const r=await api('/api/chat',{method:'POST',body:JSON.stringify({message:q,language:LANG})});const inv=r.investigation,status=inv?.status==='verified'?'VERIFIED':'REVIEW REQUIRED';const box=document.createElement('div');box.className='signal';box.innerHTML=`<b>Saarthi · ${status}</b><p>${esc(r.reply||'No response').replace(/\n/g,'<br>')}</p>${trace(inv)}${inv?`<p>${inv.evidenceQuality?.score??0}/100 evidence quality · ${inv.evidence?.length??0} evidence items</p>`:''}`;$('signals').prepend(box);if('speechSynthesis'in window&&localStorage.getItem('saarthi_tts')==='1')speak(r.reply);ping('success');agentBusy(false,t('Ready'))}catch(e){ping('error');agentBusy(false,t('Could not complete'));$('agent-status').classList.add('error');$('signals').innerHTML=`<div class="signal"><b>Could not answer</b><p>${esc(e.message)}</p></div>`}finally{$('hero-ask').disabled=false}}
async function investigate(){if(!state.hasData){show('data');return}$('investigation').innerHTML='<div class="panel" style="padding:20px"><div class="agent-trace"><div>Planning investigation…</div><div>Running evidence checks…</div><div>Verifying results…</div></div></div>';try{const r=await api('/api/investigate',{method:'POST',body:JSON.stringify({problem:'Investigate my finances and identify the strongest evidence-backed issues, changes, anomalies and review points.'})});const fs=r.findings||r.investigation?.findings||[];$('investigation').innerHTML=fs.length?fs.map((f,i)=>`<article class="finding"><span class="num">${i+1}</span><div><b>${esc(f.title||'Finding')}</b><p>${esc(f.evidence||f.text||'')}</p></div><span class="confidence">${esc(f.confidence??'—')}%</span></article>`).join(''):'<div class="panel" style="padding:20px"><b>Investigation complete.</b><p>No findings were returned. Review the verification package.</p></div>';$('investigation-meta').textContent=`Status: ${r.status||r.investigation?.status||'—'} · Evidence quality: ${r.evidenceQuality?.score??r.investigation?.evidenceQuality?.score??'—'}/100 · Gate: ${r.verification?.decisionGate||r.investigation?.verification?.decisionGate||'—'}`;ping('success')}catch(e){ping('error');$('investigation').innerHTML=`<div class="panel" style="padding:20px"><b>Investigation unavailable</b><p>${esc(e.message)}</p></div>`}}
async function decision(){const q=$('scenario').value.trim();if(!q)return;$('decision-result').innerHTML='<div class="result-box">Running Digital Twin…</div>';try{const r=await api('/api/decision',{method:'POST',body:JSON.stringify({scenario:q})});$('decision-result').innerHTML=`<div class="result-box"><b>Simulation result</b><p>Surplus: <strong>${money(r.baseline.surplus)}</strong> → <strong>${money(r.final.surplus)}</strong> (${r.delta.surplus>=0?'+':''}${money(r.delta.surplus)}).</p><p>Savings rate: ${r.baseline.savingsRate}% → ${r.final.savingsRate}%.</p><small>Simulation only. Your real ledger was not changed.</small></div>`;ping('success')}catch(e){ping('error');$('decision-result').innerHTML=`<div class="result-box"><b>Scenario unavailable</b><p>${esc(e.message)}</p></div>`}}
async function importLedger(){const f=$('ledger-file').files[0],paste=$('paste').value.trim(),problem=$('problem').value.trim();$('import-status').textContent=t('Loading…');try{let body,opt;if(f){body=new FormData();body.append('file',f);body.append('problem',problem);opt={method:'POST',body}}else{opt={method:'POST',body:JSON.stringify({data:paste,problem})}}const r=await api('/api/import',opt);state.hasData=true;render(r.analytics);await loadTx();$('import-status').textContent=`${t('Loaded')} ${r.analytics.transactionCount} ${t('usable transactions.')}`;ping('success');show('home')}catch(e){ping('error');$('import-status').textContent=e.message}}
async function inspect(){const f=$('doc-file').files[0];if(!f){$('doc-result').textContent='Choose a document first.';return}$('doc-result').innerHTML='<div class="result-box">Inspecting document…</div>';try{const fd=new FormData();fd.append('file',f);const r=await api('/api/documents/inspect',{method:'POST',body:fd});$('doc-result').innerHTML=`<div class="result-box"><b>${esc(r.document)}</b><p>${esc(r.kind)} · ${r.count} normalized rows</p><p>Facts extracted: ${Object.keys(r.facts||{}).length}. Provenance is retained for review.</p></div>`;ping('success')}catch(e){ping('error');$('doc-result').innerHTML=`<div class="result-box"><b>Could not inspect</b><p>${esc(e.message)}</p></div>`}}
function speak(text){if(!('speechSynthesis'in window)||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.98;u.pitch=1;window.speechSynthesis.speak(u)}
function setupVoice(){const B=window.SpeechRecognition||window.webkitSpeechRecognition;if(!B){$('voice-btn').title='Voice input is not supported by this browser';return}recognition=new B();recognition.lang=navigator.language||'en-IN';recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{listening=true;$('voice-btn').classList.add('listening');$('agent-status-text').textContent='Listening…'};recognition.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript;$('hero-question').value=text;if(e.results[e.results.length-1].isFinal)ask(text.trim())};recognition.onerror=()=>{listening=false;$('voice-btn').classList.remove('listening');$('agent-status-text').textContent='Voice input unavailable'};recognition.onend=()=>{listening=false;$('voice-btn').classList.remove('listening')};$('voice-btn').onclick=()=>{if(listening)recognition.stop();else{ping('tap');try{recognition.start()}catch{}}}}
async function signIn(mode){const email=$('auth-email').value.trim(),password=$('auth-password').value;if(!email||!password){$('auth-status').textContent='Enter your email and password.';ping('error');return}try{const r=await api(`/api/auth/${mode}`,{method:'POST',body:JSON.stringify({email,password})});AUTH=r.token;localStorage.setItem('saarthi_token',AUTH);$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('account-email').textContent=r.user.email;ping('success');await load()}catch(e){$('auth-status').textContent=e.message;ping('error')}}
async function demo(){const email=`demo-${makeId().slice(0,8)}@saarthi.local`,password=`Demo-${makeId()}x`;try{const r=await api('/api/auth/register',{method:'POST',body:JSON.stringify({email,password})});AUTH=r.token;localStorage.setItem('saarthi_token',AUTH);$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('account-email').textContent=r.user.email;await api('/api/load-sample',{method:'POST',body:'{}'});await load();ping('success')}catch(e){$('auth-status').textContent=e.message;ping('error')}}
function bindUI(){
  $('sign-in').onclick=()=>signIn('login');
  $('sign-up').onclick=()=>signIn('register');
  $('demo-login').onclick=demo;
  $('auth-password').onkeydown=e=>{if(e.key==='Enter')signIn('login')};
  $('auth-email').onkeydown=e=>{if(e.key==='Enter')signIn('login')};
  $('hero-ask').onclick=()=>ask($('hero-question').value.trim());
  $('hero-question').onkeydown=e=>{if(e.key==='Enter')ask($('hero-question').value.trim())};
  $('run-investigation').onclick=investigate;
  $('run-decision').onclick=decision;
  $('import').onclick=importLedger;
  $('inspect').onclick=inspect;
  $('sample').onclick=async()=>{try{await api('/api/load-sample',{method:'POST',body:'{}'});await load();show('home');ping('success')}catch(e){$('import-status').textContent=e.message;ping('error')}};
  $('logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST',body:'{}'})}catch{}AUTH='';localStorage.removeItem('saarthi_token');ping('tap');location.reload()};
  $('reset').onclick=async()=>{try{await api('/api/reset',{method:'POST',body:'{}'});await load();show('data');ping('success')}catch(e){$('signals').innerHTML=`<div class="signal"><b>Reset unavailable</b><p>${esc(e.message)}</p></div>`}};
  $('menu').onclick=()=>{$('sidebar').classList.toggle('open');ping('tap')};
  $('sound-toggle').onclick=()=>{localStorage.setItem('saarthi_sound',soundEnabled()?'0':'1');const on=soundEnabled();$('sound-toggle').innerHTML=`${t('Sound')} <strong>${on?t('ON'):t('OFF')}</strong>`;if(on)ping('success')};
  document.addEventListener('click',e=>{
    const b=e.target.closest('[data-view]');
    if(b){show(b.dataset.view);return}
    const q=e.target.closest('[data-q]');
    if(q){ask(q.dataset.q);return}
    const sc=e.target.closest('[data-scenario]');
    if(sc){$('scenario').value=sc.dataset.scenario;decision();return}
  });
  $('ledger-file')?.addEventListener('change',e=>{$('file-name').textContent=e.target.files?.[0]?.name||t('No file selected')});
  document.querySelector('[data-focus-talk]')?.addEventListener('click',()=>{$('hero-question')?.focus();$('ask-strip')?.scrollIntoView({behavior:'smooth',block:'center'});ping('tap')});
  $('language-select')?.addEventListener('change',e=>setLanguage(e.target.value));
  $('settings-open')?.addEventListener('click',openSettings);
  $('settings-close')?.addEventListener('click',closeSettings);
  document.querySelector('[data-close-settings]')?.addEventListener('click',closeSettings);
  $('settings-save')?.addEventListener('click',saveSettings);
  $('share-saarthi')?.addEventListener('click',shareSaarthi);
  updateSoundUI();
  translatePage();
}

const FINAL_I18N={
  hi:{
    'TALK TO SAARTHI':'सारथी से बात करें','“Tell me what is bothering you about your money.”':'“अपने पैसे को लेकर क्या परेशानी है, मुझे बताइए।”','No spreadsheets to decode. No finance jargon. Ask a question and Saarthi will investigate it.':'स्प्रेडशीट समझने या वित्तीय शब्दावली की जरूरत नहीं। सवाल पूछें और सारथी जांच करेगा।','Talk to Saarthi':'सारथी से बात करें','What needs attention?':'किस पर ध्यान देना है?','Explain my spending':'मेरे खर्च को समझें','Test a decision':'किसी निर्णय को परखें','Bring in my data':'अपना डेटा जोड़ें','Find what needs attention':'क्या महत्वपूर्ण है खोजें','Add data':'डेटा जोड़ें','Budget note:':'बजट नोट:','It was only ₹500.':'“यह तो सिर्फ ₹500 था।”','a sentence with a surprisingly large sequel.':'एक छोटी रकम, लेकिन इसकी कहानी अक्सर लंबी होती है।','SAARTHI GUIDE':'सारथी गाइड','“I will help you find where your money went — without asking it to write an apology letter.”':'“मैं यह पता लगाने में मदद करूंगा कि आपका पैसा कहाँ गया — बिना उससे माफ़ीनामा लिखवाए।”','Start with your data. I will guide you through':'अपने डेटा से शुरू करें। मैं आपको इस प्रक्रिया में मार्गदर्शन करूंगा','Drop or choose a spreadsheet':'स्प्रेडशीट यहाँ छोड़ें या चुनें','Excel .xlsx / .xls · CSV · JSON · TXT':'Excel .xlsx / .xls · CSV · JSON · TXT','No file selected':'कोई फ़ाइल नहीं चुनी गई','Your financial picture starts here.':'आपकी वित्तीय तस्वीर यहाँ से शुरू होती है।','Import & inspect':'डेटा जोड़ें और देखें','Make the next move':'अगला कदम उठाएँ','transactions are loaded.':'ट्रांजैक्शन लोड हो चुके हैं।','audit, compare and simulate around your financial picture.':'आपकी वित्तीय तस्वीर का ऑडिट, तुलना और सिमुलेशन किया जा सकता है।','Import a ledger or use the demo dataset to unlock Saarthi’s analysis.':'लेजर इंपोर्ट करें या डेमो डेटा इस्तेमाल करके सारथी का विश्लेषण शुरू करें।'
  },
  gu:{
    'TALK TO SAARTHI':'સારથી સાથે વાત કરો','“Tell me what is bothering you about your money.”':'“તમારા પૈસા વિશે શું ચિંતા છે, મને કહો.”','No spreadsheets to decode. No finance jargon. Ask a question and Saarthi will investigate it.':'સ્પ્રેડશીટ સમજવાની કે નાણાકીય જાર્ગનની જરૂર નથી. પ્રશ્ન પૂછો અને સારથી તપાસ કરશે.','Talk to Saarthi':'સારથી સાથે વાત કરો','What needs attention?':'કઈ બાબત પર ધ્યાન આપવું છે?','Explain my spending':'મારો ખર્ચ સમજો','Test a decision':'નિર્ણયને પરખો','Bring in my data':'મારો ડેટા ઉમેરો','Find what needs attention':'મહત્વપૂર્ણ બાબતો શોધો','Add data':'ડેટા ઉમેરો','Budget note:':'બજેટ નોંધ:','It was only ₹500.':'“એ તો ફક્ત ₹500 હતું.”','a sentence with a surprisingly large sequel.':'નાની રકમ, પણ તેની વાર્તા ઘણી લાંબી હોય છે.','SAARTHI GUIDE':'સારથી માર્ગદર્શક','“I will help you find where your money went — without asking it to write an apology letter.”':'“તમારા પૈસા ક્યાં ગયા તે શોધવામાં હું મદદ કરીશ — અને તેમને માફીનામું લખવાનું નહીં કહું.”','Start with your data. I will guide you through':'તમારા ડેટાથી શરૂઆત કરો. હું તમને આ પ્રક્રિયામાં માર્ગદર્શન આપીશ','Drop or choose a spreadsheet':'સ્પ્રેડશીટ અહીં મૂકો અથવા પસંદ કરો','Excel .xlsx / .xls · CSV · JSON · TXT':'Excel .xlsx / .xls · CSV · JSON · TXT','No file selected':'કોઈ ફાઇલ પસંદ નથી','Your financial picture starts here.':'તમારી નાણાકીય તસવીર અહીંથી શરૂ થાય છે.','Import & inspect':'ડેટા ઉમેરો અને જુઓ','Make the next move':'આગળનું પગલું લો','transactions are loaded.':'ટ્રાન્ઝેક્શન લોડ થયા છે.','audit, compare and simulate around your financial picture.':'તમારી નાણાકીય તસવીરનું ઓડિટ, સરખામણી અને સિમ્યુલેશન કરી શકાય છે.','Import a ledger or use the demo dataset to unlock Saarthi’s analysis.':'લેજર ઉમેરો અથવા ડેમો ડેટા વાપરીને સારથીનું વિશ્લેષણ શરૂ કરો.'
  }
};
function t(text){const raw=String(text??'');return FINAL_I18N[LANG]?.[raw]||I18N[LANG]?.[raw]||raw}


function translatePage(){
  document.documentElement.lang=LANG==='hi'?'hi':LANG==='gu'?'gu':'en';
  const root=document.body;
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(n=>{if(!n.parentElement || ['SCRIPT','STYLE'].includes(n.parentElement.tagName))return; const base=n.dataset.i18nOriginal??n.nodeValue.trim(); if(!base)return; n.dataset.i18nOriginal=base; const lead=n.nodeValue.match(/^\s*/)?.[0]||'',tail=n.nodeValue.match(/\s*$/)?.[0]||''; n.nodeValue=lead+t(base)+tail});
  root.querySelectorAll('input,textarea').forEach(el=>{const base=el.dataset.i18nPlaceholder??el.placeholder;if(base){el.dataset.i18nPlaceholder=base;el.placeholder=t(base)}});
  if($('language-select')) $('language-select').value=LANG; if($('settings-language')) $('settings-language').value=LANG;

  translateAllVisibleText();}
async function savePrefs(p){try{await api('/api/preferences',{method:'POST',body:JSON.stringify(p)})}catch{}}
async function loadPrefs(){try{const r=await api('/api/preferences');const p=r.preferences||{};if(p.language){LANG=p.language;localStorage.setItem(LANG_KEY,LANG)}if(typeof p.sound==='boolean')localStorage.setItem('saarthi_sound',p.sound?'1':'0');if(typeof p.tts==='boolean')localStorage.setItem('saarthi_tts',p.tts?'1':'0')}catch{}translatePage();updateSoundUI();await loadRewards()}
async function loadRewards(){try{const r=await api('/api/rewards');const x=r.rewards||{};$('reward-pill').textContent=`★ ${x.points||0} pts`;$('settings-points').textContent=`${x.points||0} points · ${x.shares||0} shares`}catch{$('reward-pill').textContent='★ 0 pts'}}
async function setLanguage(v){if(!['en','hi','gu'].includes(v))return;LANG=v;localStorage.setItem(LANG_KEY,v);await savePrefs({language:v});translatePage();if(recognition)recognition.lang=v==='hi'?'hi-IN':v==='gu'?'gu-IN':'en-IN';ping('success')}
function updateSoundUI(){const on=soundEnabled();if($('sound-toggle'))$('sound-toggle').innerHTML=`${t('Sound')} <strong>${on?t('ON'):t('OFF')}</strong>`;if($('settings-sound'))$('settings-sound').checked=on;if($('settings-tts'))$('settings-tts').checked=localStorage.getItem('saarthi_tts')==='1'}
async function shareSaarthi(){const text=LANG==='hi'?'मैं Saarthi से अपने पैसे को बेहतर समझ रहा/रही हूँ।':LANG==='gu'?'હું Saarthi સાથે મારા પૈસાને વધુ સારી રીતે સમજી રહ્યો/રહી છું.':'I’m using Saarthi to understand my money better.';try{if(navigator.share) await navigator.share({title:'Saarthi',text,url:location.origin});else await navigator.clipboard.writeText(`${text} ${location.origin}`);const r=await api('/api/rewards/share',{method:'POST',body:'{}'});$('reward-pill').textContent=`★ ${r.rewards.points} pts`;$('settings-points').textContent=`${r.rewards.points} points · ${r.rewards.shares} shares`;ping('success');alert(t('Share Saarthi to earn 25 points.'))}catch(e){if(e?.name!=='AbortError')ping('error')}}

function openSettings(){const m=$('settings-modal');m.classList.remove('hidden');$('settings-language').value=LANG;updateSoundUI();loadRewards();ping('open')}
function closeSettings(){ $('settings-modal').classList.add('hidden') }
async function saveSettings(){LANG=$('settings-language').value;localStorage.setItem(LANG_KEY,LANG);const sound=$('settings-sound').checked,tts=$('settings-tts').checked;localStorage.setItem('saarthi_sound',sound?'1':'0');localStorage.setItem('saarthi_tts',tts?'1':'0');await savePrefs({language:LANG,sound,tts});translatePage();updateSoundUI();closeSettings();ping('success')}
const oldShow=show; show=function(view){oldShow(view);translatePage();};
const oldRender=render; render=function(a){oldRender(a);translatePage()};
const oldBindUI=bindUI;
bindUI=function(){oldBindUI();$('ledger-file')?.addEventListener('change',e=>{$('file-name').textContent=e.target.files?.[0]?.name||'No file selected';});document.querySelector('[data-focus-talk]')?.addEventListener('click',()=>{$('hero-question')?.focus();$('ask-strip')?.scrollIntoView({behavior:'smooth',block:'center'});});$('language-select')?.addEventListener('change',e=>setLanguage(e.target.value));$('settings-open')?.addEventListener('click',openSettings);$('settings-close')?.addEventListener('click',closeSettings);document.querySelector('[data-close-settings]')?.addEventListener('click',closeSettings);$('settings-save')?.addEventListener('click',saveSettings);$('share-saarthi')?.addEventListener('click',shareSaarthi);updateSoundUI();translatePage();};
const oldBoot=boot;
boot=async function(){await oldBoot();if(AUTH)await loadPrefs();else{translatePage();updateSoundUI()}};

bindUI();boot();
