const $=id=>document.getElementById(id);
const makeId=()=>{try{if(window.crypto?.randomUUID)return window.crypto.randomUUID().replace(/-/g,'');if(window.crypto?.getRandomValues){const a=new Uint8Array(24);window.crypto.getRandomValues(a);return Array.from(a,x=>x.toString(16).padStart(2,'0')).join('')} }catch{} return 'saarthi_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2)};
let SESSION=localStorage.getItem('saarthi_session');if(!SESSION||!/^[a-f0-9]{16,64}$/i.test(SESSION))SESSION=makeId();localStorage.setItem('saarthi_session',SESSION);let AUTH=localStorage.getItem('saarthi_token')||'';let state={hasData:false,analytics:null};let recognition=null;let listening=false;let requestStarted=0;let timerHandle=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
async function api(path,opt={}){const headers={...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),'x-saarthi-session':SESSION,...(AUTH?{'Authorization':`Bearer ${AUTH}`}:{ }),...(opt.headers||{})};let r,j;try{r=await fetch(path,{...opt,headers});j=await r.json().catch(()=>({}));}catch(e){throw Error('Saarthi backend is unavailable. Start with npm start.')}if(!r.ok)throw Error(j?.error?.message||j?.error||`Request failed (${r.status})`);return j}
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-'+view)?.classList.add('active');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const names={home:['COMMAND CENTER','Your financial cockpit'],transactions:['CANONICAL LEDGER','Transactions'],investigate:['INVESTIGATION ENGINE','Let Saarthi investigate'],decisions:['DIGITAL TWIN','Decision Lab'],research:['RESEARCH INTELLIGENCE','Research current information'],data:['DATA WORKSPACE','Bring your financial context']};$('view-kicker').textContent=names[view][0];$('view-title').textContent=names[view][1];$('sidebar')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function render(a){state.analytics=a;if(!a){$('data-pill').textContent='No data';$('health').textContent='—';$('metrics').innerHTML='';$('flow').innerHTML='<p>Load a dataset to see your money flow.</p>';$('signals').innerHTML='';return}$('data-pill').textContent=`${a.transactionCount||0} transactions`;$('health').textContent=a.healthScore??'—';$('coverage').textContent=a.audit?.coverage||'—';$('metrics').innerHTML=[['Income',money(a.totalIncome)],['Expenses',money(a.totalExpenses)],['Surplus',money(a.netSavings)],['Savings rate',`${a.savingsRate||0}%`]].map(x=>`<div class="metric"><span>${x[0].toUpperCase()}</span><strong>${x[1]}</strong></div>`).join('');const vals=[['Income',a.totalIncome],['Expenses',a.totalExpenses],['Surplus',Math.max(0,a.netSavings)]];const max=Math.max(...vals.map(x=>Math.abs(x[1])||1));$('flow').innerHTML=vals.map(x=>`<div class="flow-row"><b>${x[0]}</b><div class="bar"><i style="width:${Math.min(100,Math.round(Math.abs(x[1])/max*100))}%"></i></div><strong>${money(x[1])}</strong></div>`).join('');const sig=(a.insights||[]).slice(0,4);$('signals').innerHTML=sig.map(x=>`<div class="signal"><b>${esc(x.title||'Signal')}</b><p>${esc(x.text||x.evidence||'')}</p></div>`).join('')||'<div class="signal"><b>No immediate signal</b><p>Run an investigation for deeper checks.</p></div>'}
async function load(){try{const j=await api('/api/state');state.hasData=j.hasData;render(j.hasData?j.analytics:null);if(j.hasData)await loadTx()}catch(e){render(null)}}async function loadTx(){const j=await api('/api/transactions');const rows=j.transactions||[];$('tx-body').innerHTML=rows.map(t=>`<tr><td>${esc(t.date)}</td><td>${esc(t.merchant||t.description)}</td><td>${esc(t.category)}</td><td>${esc(t.direction)}</td><td>${money(t.absAmount??Math.abs(t.amount))}</td><td>${esc(t.sourceRow??'—')}</td></tr>`).join('');$('tx-empty').classList.toggle('hidden',rows.length>0)}
function agentBusy(on,text='Thinking…'){const el=$('agent-status');el.classList.toggle('busy',on);el.classList.remove('error');$('agent-status-text').textContent=text;if(on){requestStarted=performance.now();clearInterval(timerHandle);timerHandle=setInterval(()=>{$('agent-timer').textContent=`${((performance.now()-requestStarted)/1000).toFixed(1)}s`},100)}else{clearInterval(timerHandle);$('agent-timer').textContent=''}}
function trace(investigation){if(!investigation)return '';const steps=investigation.plan?.steps||[];const labels={investigate_finances:'Map finances',get_financial_summary:'Calculate summary',audit_transactions:'Audit ledger',find_category_spending:'Inspect categories',compare_months:'Compare periods',calculate_goal:'Test goal',calculate_affordability:'Check affordability',run_what_if:'Run simulation'};return `<div class="agent-trace">${steps.map((s,i)=>`<div class="trace-step done">${esc(labels[s]||s)}</div>`).join('')}</div>`}
async function ask(q){if(!q)return;show('home');$('hero-question').value=q;$('hero-ask').disabled=true;agentBusy(true,'Investigating your request');try{const r=await api('/api/chat',{method:'POST',body:JSON.stringify({message:q})});const inv=r.investigation;const status=inv?.status==='verified'?'VERIFIED':'REVIEW REQUIRED';const box=document.createElement('div');box.className='result-box';box.innerHTML=`<span class="agent-badge">${status}</span><b>Saarthi</b><p>${esc(r.reply||'No response').replace(/\n/g,'<br>')}</p>${trace(inv)}${inv?`<div class="evidence-mini">${inv.evidenceQuality?.score??0}/100 evidence quality · ${inv.evidence?.length??0} evidence items · ${esc(inv.verification?.decisionGate||'—')}</div>`:''}`;$('signals').prepend(box);if('speechSynthesis' in window&&localStorage.getItem('saarthi_tts')==='1')speak(r.reply);agentBusy(false,'Ready')}catch(e){agentBusy(false,'Could not complete');$('agent-status').classList.add('error');$('signals').innerHTML=`<div class="signal"><b>Could not answer</b><p>${esc(e.message)}</p></div>`}finally{$('hero-ask').disabled=false}}
async function investigate(){if(!state.hasData){show('data');return}$('investigation').innerHTML='<div class="card"><div class="agent-trace"><div class="trace-step live">Planning investigation</div><div class="trace-step wait">Running evidence checks</div><div class="trace-step wait">Verifying results</div></div></div>';try{const r=await api('/api/investigate',{method:'POST',body:JSON.stringify({problem:'Investigate my finances and identify the strongest evidence-backed issues, changes, anomalies and review points.'})});const fs=r.findings||r.investigation?.findings||[];$('investigation').innerHTML=(fs.length?fs:[]).map((f,i)=>`<article class="finding"><span class="num">${i+1}</span><div><b>${esc(f.title||'Finding')}</b><p>${esc(f.evidence||f.text||'')}</p></div><span class="confidence">${esc(f.confidence??'—')}%</span></article>`).join('')||'<div class="card"><b>Investigation complete.</b><p>Review the evidence package and verification status below.</p></div>';$('investigation-meta').innerHTML=`Status: <strong>${esc(r.status||r.investigation?.status||'—')}</strong> · Evidence quality: ${r.evidenceQuality?.score??r.investigation?.evidenceQuality?.score??'—'}/100 · Gate: ${esc(r.verification?.decisionGate||r.investigation?.verification?.decisionGate||'—')}`;}catch(e){$('investigation').innerHTML=`<div class="card"><b>Investigation unavailable</b><p>${esc(e.message)}</p></div>`}}
async function decision(){const q=$('scenario').value.trim();if(!q)return;$('decision-result').innerHTML='<div class="result-box">Running Digital Twin…</div>';try{const r=await api('/api/decision',{method:'POST',body:JSON.stringify({scenario:q})});$('decision-result').innerHTML=`<div class="result-box"><b>Simulation result</b><p>Surplus: <strong>${money(r.baseline.surplus)}</strong> → <strong>${money(r.final.surplus)}</strong> (${r.delta.surplus>=0?'+':''}${money(r.delta.surplus)}).</p><p>Savings rate: ${r.baseline.savingsRate}% → ${r.final.savingsRate}%.</p><small>This is a simulation. Your real ledger was not changed.</small></div>`}catch(e){$('decision-result').innerHTML=`<div class="result-box"><b>Scenario unavailable</b><p>${esc(e.message)}</p></div>`}}
async function research(){const q=$('research-query').value.trim();if(!q)return;$('research-result').innerHTML='<div class="result-box">Researching current sources…</div>';try{const r=await api('/api/research',{method:'POST',body:JSON.stringify({query:q})});$('research-result').innerHTML=`<div class="result-box"><b>Research result</b><p>${esc(r.answer||'').replace(/\n/g,'<br>')}</p><small>${r.generatedAt?'Retrieved '+esc(r.generatedAt):'Public-source research'} · Verify important rules, fees and deadlines against the cited source.</small></div>`}catch(e){$('research-result').innerHTML=`<div class="result-box"><b>Research unavailable</b><p>${esc(e.message)}</p></div>`}}
async function importLedger(){const f=$('ledger-file').files[0],paste=$('paste').value.trim(),problem=$('problem').value.trim();$('import-status').textContent='Loading…';try{let body,opt;if(f){body=new FormData();body.append('file',f);body.append('problem',problem);opt={method:'POST',body}}else{opt={method:'POST',body:JSON.stringify({data:paste,problem})}}const r=await api('/api/import',opt);state.hasData=true;render(r.analytics);await loadTx();$('import-status').textContent=`Loaded ${r.analytics.transactionCount} usable transactions.`;show('home')}catch(e){$('import-status').textContent=e.message}}
async function inspect(){const f=$('doc-file').files[0];if(!f)return;$('doc-result').innerHTML='Inspecting document…';try{const fd=new FormData();fd.append('file',f);const r=await api('/api/documents/inspect',{method:'POST',body:fd});$('doc-result').innerHTML=`<div class="result-box"><b>${esc(r.document)}</b><p>${esc(r.kind)} · ${r.count} normalized rows</p><p>Facts extracted: ${Object.keys(r.facts||{}).length}. Provenance is retained for review.</p></div>`}catch(e){$('doc-result').innerHTML=`<div class="result-box"><b>Could not inspect</b><p>${esc(e.message)}</p></div>`}}
function speak(text){if(!('speechSynthesis'in window)||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.98;u.pitch=1;window.speechSynthesis.speak(u)}
function setupVoice(){const B=window.SpeechRecognition||window.webkitSpeechRecognition;if(!B){$('voice-btn').title='Voice input is not supported by this browser';return}recognition=new B();recognition.lang=navigator.language||'en-IN';recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{listening=true;$('voice-btn').classList.add('listening');$('agent-status-text').textContent='Listening…'};recognition.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript;$('hero-question').value=text;if(e.results[e.results.length-1].isFinal)ask(text.trim())};recognition.onerror=()=>{listening=false;$('voice-btn').classList.remove('listening');$('agent-status-text').textContent='Voice input unavailable'};recognition.onend=()=>{listening=false;$('voice-btn').classList.remove('listening');if(!$('hero-question').value.trim())$('agent-status-text').textContent='Ready'};$('voice-btn').onclick=()=>{if(listening)recognition.stop();else recognition.start()}}
async function signIn(mode){const email=$('auth-email').value.trim(),password=$('auth-password').value;if(!email||!password){$('auth-status').textContent='Enter your email and password.';return}try{const r=await api(`/api/auth/${mode}`,{method:'POST',body:JSON.stringify({email,password})});AUTH=r.token;localStorage.setItem('saarthi_token',AUTH);$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('account-email').textContent=r.user.email;load();}catch(e){$('auth-status').textContent=e.message}}
function bindUI(){
$('sign-in').onclick=()=>signIn('login');
$('sign-up').onclick=()=>signIn('register');
$('demo-login').onclick=async()=>{const email=`demo-${makeId().slice(0,8)}@saarthi.local`,password=`Demo-${makeId()}x`;try{const r=await api('/api/auth/register',{method:'POST',body:JSON.stringify({email,password})});AUTH=r.token;localStorage.setItem('saarthi_token',AUTH);$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('account-email').textContent=r.user.email;await api('/api/load-sample',{method:'POST',body:'{}'});await load()}catch(e){$('auth-status').textContent=e.message}};
$('auth-password').onkeydown=e=>{if(e.key==='Enter')signIn('login')};
$('auth-email').onkeydown=e=>{if(e.key==='Enter')signIn('login')};
$('hero-ask').onclick=()=>ask($('hero-question').value.trim());
$('hero-question').onkeydown=e=>{if(e.key==='Enter')ask($('hero-question').value.trim())};
document.querySelectorAll('.nav,[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>ask(b.dataset.q));$('run-investigation').onclick=investigate;$('run-decision').onclick=decision;$('run-research').onclick=research;$('import').onclick=importLedger;$('inspect').onclick=inspect;$('sample').onclick=async()=>{try{await api('/api/load-sample',{method:'POST',body:'{}'});await load();show('home')}catch(e){$('import-status').textContent=e.message}};$('logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST',body:'{}'})}catch{} AUTH='';localStorage.removeItem('saarthi_token');location.reload()};$('reset').onclick=async()=>{try{await api('/api/reset',{method:'POST',body:'{}'});await load();show('data')}catch(e){$('signals').innerHTML=`<div class="signal"><b>Reset unavailable</b><p>${esc(e.message)}</p></div>`}};$('menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>{$('scenario').value=b.dataset.scenario;decision()});setupVoice();
}

if(AUTH){api('/api/auth/me').then(r=>{$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('account-email').textContent=r.user.email;load()}).catch(()=>{AUTH='';localStorage.removeItem('saarthi_token')})}
bindUI();
