const params=new URLSearchParams(location.search);const key=params.get('feature')||'money';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const session=localStorage.getItem('saarthi_session')||'';const token=localStorage.getItem('saarthi_token')||'';
async function api(path,opt={}){const headers={...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(session?{'x-saarthi-session':session}:{}),...(token?{'Authorization':`Bearer ${token}`}:{})};const r=await fetch(path,{...opt,headers});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j?.error?.message||j?.error||`Request failed (${r.status})`);return j}
function go(f){location.href=`feature.html?feature=${encodeURIComponent(f)}`}
$('#back').onclick=()=>history.back();$('#undo').onclick=()=>history.back();$('#redo').onclick=()=>history.forward();
const configs={
 money:{eyebrow:'MONEY MIRROR',title:'See where your money goes.',subtitle:'A simple picture of your income, spending and surplus — no spreadsheet detective work needed.',render:money},
 hisaab:{eyebrow:'HISAAB DETECTIVE',title:"Let's find the missing piece.",subtitle:'Saarthi checks the numbers and flags gaps for review. No invented transactions.',render:hisaab},
 whatif:{eyebrow:'MONEY TIME MACHINE',title:'Try it before you do it.',subtitle:'Change a scenario and see the possible impact without changing your real ledger.',render:whatif},
 goals:{eyebrow:'FUTURE FUND',title:'Small steps, big plans.',subtitle:'Turn a target into a realistic monthly plan using the financial picture Saarthi already knows.',render:goals},
 afford:{eyebrow:'WALLET CHECK',title:"Let's do the math.",subtitle:'Test a purchase against your current financial picture before you commit.',render:afford},
 loan:{eyebrow:'BORROW SMART',title:'Check the numbers first.',subtitle:'Explore a loan scenario using the existing affordability and decision tools.',render:loan},
 safety:{eyebrow:'MONEY SHIELD',title:'A second look never hurts.',subtitle:'Spot unusual patterns and learn what deserves a closer look.',render:safety},
 kyc:{eyebrow:'KYC BUDDY',title:'Forms are boring. Let’s fix that.',subtitle:'Bring a supported financial document and Saarthi can help you understand what you are looking at.',render:kyc},
 data:{eyebrow:'FEED SAARTHI',title:'Bring your numbers along.',subtitle:'Upload Excel, CSV, JSON or text, or paste a few rows. Your existing parser does the heavy lifting.',render:data},
 pulse:{eyebrow:'MONEY PULSE',title:'How are things really going?',subtitle:'A quick health check from your recent financial patterns.',render:pulse},
 forecast:{eyebrow:'MONEY FORECAST',title:'What might happen next?',subtitle:'Your recent spending gives us a few clues. This is an estimate, not a promise.',render:forecast},
 match:{eyebrow:'SMART MATCH',title:'The right product, when it fits.',subtitle:'A banking recommendation should solve a real need — not just become another pop-up.',render:match},
 ask:{eyebrow:'SAARTHI SAYS',title:'Just ask. Saarthi listens.',subtitle:'Ask a normal question. The existing AI and financial tools handle the heavy lifting.',render:ask},
 talk:{eyebrow:'TALK IT OUT',title:"Say it, don't type it.",subtitle:'Use your browser microphone and send your question to Saarthi.',render:talk},
 brief:{eyebrow:'MONEY SNAPSHOT',title:'Your money, at a glance.',subtitle:'A compact financial brief generated from the existing backend analysis.',render:brief}
};
const cfg=configs[key]||configs.money;$('#eyebrow').textContent=cfg.eyebrow;$('#title').textContent=cfg.title;$('#subtitle').textContent=cfg.subtitle;$('#crumb').textContent=cfg.eyebrow;
function panel(title,text,body=''){return `<article class="feature-panel"><div class="eyebrow">SAARTHI</div><h2>${title}</h2><p>${text}</p>${body}</article>`}
function navCards(){return `<div class="feature-grid-inner"><a class="feature-card" href="feature.html?feature=money"><span class="icon">💰</span><h3>Money Mirror</h3><p>See where your money goes.</p></a><a class="feature-card" href="feature.html?feature=hisaab"><span class="icon">🕵️</span><h3>Hisaab Detective</h3><p>Let's find the missing piece.</p></a><a class="feature-card" href="feature.html?feature=whatif"><span class="icon">🧪</span><h3>Money Time Machine</h3><p>Try it before you do it.</p></a><a class="feature-card" href="feature.html?feature=goals"><span class="icon">🎯</span><h3>Future Fund</h3><p>Small steps, big plans.</p></a><a class="feature-card" href="feature.html?feature=afford"><span class="icon">💳</span><h3>Wallet Check</h3><p>Let's do the math.</p></a><a class="feature-card" href="feature.html?feature=loan"><span class="icon">🏦</span><h3>Borrow Smart</h3><p>Check the numbers first.</p></a><a class="feature-card" href="feature.html?feature=safety"><span class="icon">🛡️</span><h3>Money Shield</h3><p>A second look never hurts.</p></a><a class="feature-card" href="feature.html?feature=kyc"><span class="icon">🪪</span><h3>KYC Buddy</h3><p>Forms are boring. Let's fix that.</p></a><a class="feature-card" href="feature.html?feature=data"><span class="icon">📁</span><h3>Feed Saarthi</h3><p>Give Saarthi your numbers.</p></a><a class="feature-card" href="feature.html?feature=pulse"><span class="icon">🚦</span><h3>Money Pulse</h3><p>How are things really going?</p></a><a class="feature-card" href="feature.html?feature=forecast"><span class="icon">🔮</span><h3>Money Forecast</h3><p>Your recent patterns give clues.</p></a><a class="feature-card" href="feature.html?feature=match"><span class="icon">🧠</span><h3>Smart Match</h3><p>The right product, when it fits.</p></a><a class="feature-card" href="feature.html?feature=ask"><span class="icon">💬</span><h3>Saarthi Says</h3><p>Just ask. Saarthi listens.</p></a><a class="feature-card" href="feature.html?feature=talk"><span class="icon">🎙️</span><h3>Talk It Out</h3><p>Say it, don't type it.</p></a><a class="feature-card" href="feature.html?feature=brief"><span class="icon">📊</span><h3>Money Snapshot</h3><p>Your money, at a glance.</p></a></div>`}
async function dashboard(){return api('/api/dashboard')}
async function money(){try{const r=await dashboard(),a=r;$('#content').innerHTML=panel('Your financial picture','Pulled from the same backend used by the main Saarthi cockpit.',`<div class="metric-row"><div class="mini-metric"><small>INCOME</small><b>${moneyFmt(a.totalIncome)}</b></div><div class="mini-metric"><small>SPENDING</small><b>${moneyFmt(a.totalExpenses)}</b></div><div class="mini-metric"><small>SURPLUS</small><b>${moneyFmt(a.netSavings)}</b></div></div><div class="feature-actions"><a class="feature-btn" href="index.html">Open full cockpit →</a><a class="feature-btn alt" href="feature.html?feature=forecast">What might happen next?</a></div>`)}catch(e){error(e)}}
const moneyFmt=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
async function hisaab(){ $('#content').innerHTML=panel('Find Missing Hisaab','Run the existing investigation engine against your loaded financial data.','<button class="feature-btn" id="run">Start investigation →</button><div id="out"></div>');$('#run').onclick=async()=>{out.innerHTML='<div class="loading">Checking the ledger → comparing → verifying…</div>';try{const r=await api('/api/investigate',{method:'POST',body:JSON.stringify({problem:'Find missing hisaab, unexplained differences, suspicious gaps and review points in my finances.'})});const inv=r.investigation||r;out.innerHTML=`<div class="result-note"><b>${esc(r.status||inv.status||'Investigation complete')}</b><br>Evidence quality: ${esc(r.evidenceQuality?.score??inv.evidenceQuality?.score??'—')}/100<br>${(r.findings||inv.findings||[]).map(x=>`• ${esc(x.title||'Finding')}: ${esc(x.evidence||x.text||'')}`).join('<br>')||'No specific findings returned.'}</div>`}catch(e){out.innerHTML=`<div class="error-note">${esc(e.message)}</div>`}}}
async function whatif(){ $('#content').innerHTML=panel('What are you considering?','Try a change without touching your real ledger.',`<div class="chat-box"><input class="feature-input" id="q" placeholder="Reduce food spending by 20%"><button class="feature-btn" id="go">Compare →</button></div><div id="out"></div>`);$('#go').onclick=runWhat;if(!session){/* backend may still use its default/demo session */}function runWhat(){const q=$('#q').value.trim();if(!q)return;$('#out').innerHTML='<div class="loading">Running the scenario…</div>';api('/api/decision',{method:'POST',body:JSON.stringify({scenario:q})}).then(r=>{$('#out').innerHTML=`<div class="result-note"><b>Scenario result</b><br>Baseline surplus: ${moneyFmt(r.baseline?.surplus)}<br>New surplus: ${moneyFmt(r.final?.surplus)}<br>Impact: ${moneyFmt((r.final?.surplus??0)-(r.baseline?.surplus??0))}</div>`}).catch(e=>$('#out').innerHTML=`<div class="error-note">${esc(e.message)}</div>`)}}
function goals(){ $('#content').innerHTML=panel('Build a simple goal plan','Tell Saarthi what you want to save and by when.',`<div class="chat-box"><input class="feature-input" id="q" placeholder="I need ₹50,000 in 5 months"><button class="feature-btn" id="go">Plan →</button></div><div id="out"></div>`);$('#go').onclick=()=>askApi($('#q').value,'Goal planning')}
function afford(){ $('#content').innerHTML=panel('Can I afford this?','Ask in plain English. Saarthi can use the existing financial context and decision tools.',`<div class="chat-box"><input class="feature-input" id="q" placeholder="Can I afford a ₹40,000 phone?"><button class="feature-btn" id="go">Check →</button></div><div id="out"></div>`);$('#go').onclick=()=>askApi($('#q').value,'Affordability check')}
function loan(){ $('#content').innerHTML=panel('Borrow Smart','Use the existing scenario engine to test loan-related affordability. Current lender rates or rules are not fabricated here.',`<div class="chat-box"><input class="feature-input" id="q" placeholder="Can I handle a ₹5 lakh loan over 5 years?"><button class="feature-btn" id="go">Check →</button></div><div id="out"></div>`);$('#go').onclick=()=>askApi($('#q').value,'Loan affordability')}
function safety(){ $('#content').innerHTML=panel('Money Shield','Saarthi flags unusual patterns as signals for review — not proof of fraud.',`<a class="feature-btn" href="feature.html?feature=hisaab">Run an investigation →</a><a class="back-home" href="feature.html?feature=pulse">See Money Pulse →</a>`)}
function kyc(){ $('#content').innerHTML=panel('Bring a document','Use the existing document-inspection route for supported files.','<a class="feature-btn" href="feature.html?feature=data">Choose a document →</a><div class="result-note">Supported formats include PDF, XLSX/XLS, CSV, JSON and text in the current project.</div>')}
function data(){ $('#content').innerHTML=panel('Add your financial data','The main data workspace already supports Excel, CSV, JSON and text. This page is a quick route into it.',`<a class="feature-btn" href="index.html">Open Add / Manage Data →</a><div class="result-note">Your existing parser normalizes imported rows into the canonical ledger used by analysis, audit and decisions.</div>`)}
async function pulse(){try{const r=await dashboard();const a=r;$('#content').innerHTML=panel('Your Money Pulse','A quick read from the current numbers.',`<div class="metric-row"><div class="mini-metric"><small>SAVINGS RATE</small><b>${esc(a.savingsRate??'—')}%</b></div><div class="mini-metric"><small>TRANSACTIONS</small><b>${esc(a.transactionCount??'—')}</b></div><div class="mini-metric"><small>STATUS</small><b>${a.netSavings>=0?'🙂':'⚠️'}</b></div></div><div class="result-note">This is a financial signal, not a credit score.</div>`)}catch(e){error(e)}}
async function forecast(){try{const r=await dashboard(),a=r;const exp=Number(a.totalExpenses)||0,inc=Number(a.totalIncome)||0,sur=Number(a.netSavings)||0;$('#content').innerHTML=panel('What might happen next?','Based on the current aggregate pattern, not a guaranteed forecast.',`<div class="metric-row"><div class="mini-metric"><small>CURRENT SPENDING</small><b>${moneyFmt(exp)}</b></div><div class="mini-metric"><small>CURRENT SURPLUS</small><b>${moneyFmt(sur)}</b></div><div class="mini-metric"><small>IF PATTERN CONTINUES</small><b>${moneyFmt(Math.max(0,sur))}</b></div></div><div class="result-note">Saarthi is using your recent financial picture as a clue. It is an estimate, not a promise.</div>`)}catch(e){error(e)}}
function match(){ $('#content').innerHTML=panel('Smart Match','A real recommendation should start with a real need. For the hackathon, this workspace explains the decision logic without pretending a bank product is approved.',`<div class="list"><div class="list-row"><span>Financial need</span><span>Understand →</span></div><div class="list-row"><span>Current commitments</span><span>Check →</span></div><div class="list-row"><span>Affordability</span><span>Stress-test →</span></div><div class="list-row"><span>Product fit</span><span>Explain why →</span></div></div><div class="feature-actions"><a class="feature-btn" href="feature.html?feature=afford">Check affordability</a><a class="feature-btn alt" href="feature.html?feature=loan">Borrow Smart</a></div>`)}
function ask(){ $('#content').innerHTML=panel('Ask anything','Questions can be normal, messy and human.',`<div class="chat-box"><input class="feature-input" id="q" placeholder="Why am I saving less this month?"><button class="feature-btn" id="go">Ask →</button></div><div id="out"></div><div class="result-note">Try: “Where is my money going?”, “Can I afford ₹30,000?”, or “Why did my spending increase?”</div>`);$('#go').onclick=()=>askApi($('#q').value,'Saarthi')}
function talk(){ $('#content').innerHTML=panel('Talk to Saarthi','Use your browser speech recognition, then send the transcript to the same AI route.',`<button class="feature-btn" id="mic">🎙 Start listening</button><div id="heard" class="result-note">Nothing heard yet.</div><div class="chat-box" style="margin-top:12px"><input class="feature-input" id="q" placeholder="Your transcript appears here"><button class="feature-btn" id="go">Ask →</button></div><div id="out"></div>`);let rec=null;$('#mic').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#heard').textContent='Speech recognition is not supported by this browser. You can still type your question.';return}rec=new SR();rec.lang=(localStorage.getItem('saarthi_language')||'en')==='hi'?'hi-IN':(localStorage.getItem('saarthi_language')||'en')==='gu'?'gu-IN':'en-IN';rec.onresult=e=>{$('#q').value=e.results[0][0].transcript;$('#heard').textContent='Heard: '+e.results[0][0].transcript};rec.start()};$('#go').onclick=()=>askApi($('#q').value,'Talk to Saarthi')}
async function brief(){try{const r=await api('/api/brief');$('#content').innerHTML=panel('Money Snapshot','A compact view generated by the existing backend brief endpoint.',`<div class="result-note">${esc(JSON.stringify(r,null,2))}</div>`)}catch(e){error(e)}}
async function askApi(q,label){if(!q?.trim())return;$('#out').innerHTML='<div class="loading">Saarthi is thinking…</div>';try{const r=await api('/api/chat',{method:'POST',body:JSON.stringify({message:q,language:localStorage.getItem('saarthi_language')||'en'})});$('#out').innerHTML=`<div class="result-note"><b>${esc(label)}</b><br>${esc(r.reply||'No response').replace(/\n/g,'<br>')}</div>`}catch(e){$('#out').innerHTML=`<div class="error-note">${esc(e.message)}</div>`}}
function error(e){$('#content').innerHTML=panel('Saarthi needs your data','This workspace uses the existing backend. Load data from the main Add Data page first if you have not done so.',`<div class="error-note">${esc(e.message)}</div><a class="back-home" href="feature.html?feature=data">Add data →</a>`)}
cfg.render();
